require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SeasonsController do

  # This should return the minimal set of attributes required to create a valid
  # Season. As you add validations to Season, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all seasons as @seasons" do
      season = Season.create! valid_attributes
      get :index
      assigns(:seasons).should eq([season])
    end
  end

  describe "GET show" do
    it "assigns the requested season as @season" do
      season = Season.create! valid_attributes
      get :show, :id => season.id.to_s
      assigns(:season).should eq(season)
    end
  end

  describe "GET new" do
    it "assigns a new season as @season" do
      get :new
      assigns(:season).should be_a_new(Season)
    end
  end

  describe "GET edit" do
    it "assigns the requested season as @season" do
      season = Season.create! valid_attributes
      get :edit, :id => season.id.to_s
      assigns(:season).should eq(season)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Season" do
        expect {
          post :create, :season => valid_attributes
        }.to change(Season, :count).by(1)
      end

      it "assigns a newly created season as @season" do
        post :create, :season => valid_attributes
        assigns(:season).should be_a(Season)
        assigns(:season).should be_persisted
      end

      it "redirects to the created season" do
        post :create, :season => valid_attributes
        response.should redirect_to(Season.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved season as @season" do
        # Trigger the behavior that occurs when invalid params are submitted
        Season.any_instance.stub(:save).and_return(false)
        post :create, :season => {}
        assigns(:season).should be_a_new(Season)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Season.any_instance.stub(:save).and_return(false)
        post :create, :season => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested season" do
        season = Season.create! valid_attributes
        # Assuming there are no other seasons in the database, this
        # specifies that the Season created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Season.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => season.id, :season => {'these' => 'params'}
      end

      it "assigns the requested season as @season" do
        season = Season.create! valid_attributes
        put :update, :id => season.id, :season => valid_attributes
        assigns(:season).should eq(season)
      end

      it "redirects to the season" do
        season = Season.create! valid_attributes
        put :update, :id => season.id, :season => valid_attributes
        response.should redirect_to(season)
      end
    end

    describe "with invalid params" do
      it "assigns the season as @season" do
        season = Season.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Season.any_instance.stub(:save).and_return(false)
        put :update, :id => season.id.to_s, :season => {}
        assigns(:season).should eq(season)
      end

      it "re-renders the 'edit' template" do
        season = Season.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Season.any_instance.stub(:save).and_return(false)
        put :update, :id => season.id.to_s, :season => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested season" do
      season = Season.create! valid_attributes
      expect {
        delete :destroy, :id => season.id.to_s
      }.to change(Season, :count).by(-1)
    end

    it "redirects to the seasons list" do
      season = Season.create! valid_attributes
      delete :destroy, :id => season.id.to_s
      response.should redirect_to(seasons_url)
    end
  end

end
