require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TicketHoldersController do

  # This should return the minimal set of attributes required to create a valid
  # TicketHolder. As you add validations to TicketHolder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all ticket_holders as @ticket_holders" do
      ticket_holder = TicketHolder.create! valid_attributes
      get :index
      assigns(:ticket_holders).should eq([ticket_holder])
    end
  end

  describe "GET show" do
    let(:ticket_holder) { TicketHolder.create!(valid_attributes) }

    it "assigns the requested ticket_holder as @ticket_holder" do
      get :show, :id => ticket_holder.id.to_s
      assigns(:ticket_holder).should eq(ticket_holder)
    end

    context '@games' do
      before do
        Game.create!
        Game.create!.tap do |game|
          game.tickets.each do |ticket|
            ticket.update_attributes!(:ticket_holder_id => ticket_holder.id)
          end
        end
        Game.create!.tap do |game|
          game.tickets.each do |ticket|
            ticket.update_attributes!(:ticket_holder_id => ticket_holder.id)
          end
        end
      end

      it 'is assigned @ticket_holder.games' do
        get :show, :id => ticket_holder.id.to_s
        assigns(:games).should eq(ticket_holder.games)
      end
    end
  end

  describe "GET new" do
    it "assigns a new ticket_holder as @ticket_holder" do
      get :new
      assigns(:ticket_holder).should be_a_new(TicketHolder)
    end

    context '@seasons' do
      before do
        Season.create!(:years => '2011-12')
        Season.create!(:years => '2012-13')
      end

      it 'is assigned available seasons' do
        get :new
        assigns(:seasons).should eq(Season.all)
      end
    end
  end

  describe "GET edit" do
    let(:ticket_holder) { TicketHolder.create! valid_attributes }

    it "assigns the requested ticket_holder as @ticket_holder" do
      get :edit, :id => ticket_holder.id.to_s
      assigns(:ticket_holder).should eq(ticket_holder)
    end

    context '@seasons' do
      before do
        Season.create!(:years => '2011-12')
        Season.create!(:years => '2012-13')
      end

      it 'is assigned available seasons' do
        get :edit, :id => ticket_holder.id.to_s
        assigns(:seasons).should eq(Season.all)
      end
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TicketHolder" do
        expect {
          post :create, :ticket_holder => valid_attributes
        }.to change(TicketHolder, :count).by(1)
      end

      it "assigns a newly created ticket_holder as @ticket_holder" do
        post :create, :ticket_holder => valid_attributes
        assigns(:ticket_holder).should be_a(TicketHolder)
        assigns(:ticket_holder).should be_persisted
      end

      it "redirects to the created ticket_holder" do
        post :create, :ticket_holder => valid_attributes
        response.should redirect_to(TicketHolder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ticket_holder as @ticket_holder" do
        # Trigger the behavior that occurs when invalid params are submitted
        TicketHolder.any_instance.stub(:save).and_return(false)
        post :create, :ticket_holder => {}
        assigns(:ticket_holder).should be_a_new(TicketHolder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TicketHolder.any_instance.stub(:save).and_return(false)
        post :create, :ticket_holder => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ticket_holder" do
        ticket_holder = TicketHolder.create! valid_attributes
        # Assuming there are no other ticket_holders in the database, this
        # specifies that the TicketHolder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TicketHolder.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ticket_holder.id, :ticket_holder => {'these' => 'params'}
      end

      it "assigns the requested ticket_holder as @ticket_holder" do
        ticket_holder = TicketHolder.create! valid_attributes
        put :update, :id => ticket_holder.id, :ticket_holder => valid_attributes
        assigns(:ticket_holder).should eq(ticket_holder)
      end

      it "redirects to the ticket_holder" do
        ticket_holder = TicketHolder.create! valid_attributes
        put :update, :id => ticket_holder.id, :ticket_holder => valid_attributes
        response.should redirect_to(ticket_holder)
      end
    end

    describe "with invalid params" do
      it "assigns the ticket_holder as @ticket_holder" do
        ticket_holder = TicketHolder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TicketHolder.any_instance.stub(:save).and_return(false)
        put :update, :id => ticket_holder.id.to_s, :ticket_holder => {}
        assigns(:ticket_holder).should eq(ticket_holder)
      end

      it "re-renders the 'edit' template" do
        ticket_holder = TicketHolder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TicketHolder.any_instance.stub(:save).and_return(false)
        put :update, :id => ticket_holder.id.to_s, :ticket_holder => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ticket_holder" do
      ticket_holder = TicketHolder.create! valid_attributes
      expect {
        delete :destroy, :id => ticket_holder.id.to_s
      }.to change(TicketHolder, :count).by(-1)
    end

    it "redirects to the ticket_holders list" do
      ticket_holder = TicketHolder.create! valid_attributes
      delete :destroy, :id => ticket_holder.id.to_s
      response.should redirect_to(ticket_holders_url)
    end
  end

end
